In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVC

In [3]:
df=pd.read_csv("/kaggle/input/car-price-predictionused-cars/car data.csv")

In [5]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [16]:
df=pd.get_dummies(df)

In [17]:
df

,Year,Selling_Price,Present_Price,Driven_kms,Owner,Car_Name_800,Car_Name_Activa 3g,Car_Name_Activa 4g,Car_Name_Bajaj ct 100,Car_Name_Bajaj Avenger 150,...,Car_Name_vitara brezza,Car_Name_wagon r,Car_Name_xcent,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Selling_type_Dealer,Selling_type_Individual,Transmission_Automatic,Transmission_Manual
0,2014,3.35,5.59,27000,0,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True
1,2013,4.75,9.54,43000,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True
2,2017,7.25,9.85,6900,0,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True
3,2011,2.85,4.15,5200,0,False,False,False,False,False,...,False,True,False,False,False,True,True,False,False,True
4,2014,4.60,6.87,42450,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,2016,9.50,11.60,33988,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True
297,2015,4.00,5.90,60000,0,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True
298,2009,3.35,11.00,87934,0,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True
299,2017,11.50,12.50,9000,0,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True
300,2016,5.30,5.90,5464,0,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,True

In [18]:
X=df.drop(columns=["Present_Price"])
Y=df["Present_Price"]

In [19]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [24]:
for i in [RandomForestRegressor(),GradientBoostingRegressor(),AdaBoostRegressor(),KNeighborsRegressor()]:
    random_reg=i
    random_reg.fit(X_train,Y_train)
    print(f"The accuracy of {i}:",random_reg.score(X_test,Y_test))

The accuracy of RandomForestRegressor(): 0.8763533640592236
The accuracy of GradientBoostingRegressor(): 0.9181928382510044
The accuracy of AdaBoostRegressor(): 0.8675042760442699
The accuracy of KNeighborsRegressor(): 0.11161595051826934