In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import BernoulliNB

In [2]:
df=pd.read_csv("/kaggle/input/indonesia-national-science-olympiad-osn/osn.csv")
df

,Unnamed: 0,Nama Peserta,Gender,Sekolah,Provinsi,Kab/Kota,Bidang,Jenjang Lomba,Jenjang Sekolah,Kelas,Medali,Prize Tambahan,Tahun
0,0,Gangsar Lintas Damai,L,MA Amanatul Ummah,Jawa Timur,Kota Surabaya,Biologi,SMA,SMA,11.0,Partisipan,NaN,2016
1,1,Muhammad Khairul Ihsan,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Partisipan,NaN,2021
2,2,Farhannur,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Emas,NaN,2022
3,3,Muhammad Fathoni,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Fisika,SMA,SMA,11.0,Partisipan,NaN,2022
4,4,Rahmat MI,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Kimia,SMA,SMA,11.0,Partisipan,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19322,19322,Fitri Julia Simamora,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,NaN,2024
19323,19323,Jonathan Kevin Aruan,L,SMPN 6 Sentajo,Riau,Kab. Kuantan Singingi,IPS,SMP,SMP,NaN,Partisipan,NaN,2016
19324,19324,Mely Winda Sihite,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,NaN,2024
19325,19325,Jelita Fazira,P,SMPN 4 Pantai Labu Satu Atap,Sumatera Utara,Kab. Deli Serdang,IPS,SMP,SMP,NaN,Partisipan,NaN,2021
19326,19326,Pether Kanisius Gajah,L,SMPN 4 Parlilitan,Sumatera Utara,Kab. Humbang Hasundutan,IPS,SMP,SMP,NaN,Partisipan,NaN,2020

In [3]:
df.isnull().sum()

Unnamed: 0             0
Nama Peserta           0
Gender                 0
Sekolah                0
Provinsi               0
Kab/Kota               0
Bidang                 0
Jenjang Lomba          0
Jenjang Sekolah        0
Kelas               4475
Medali                 0
Prize Tambahan     19106
Tahun                  0
dtype: int64

In [4]:
df=df.drop(columns=["Prize Tambahan"])
df=df.dropna(how="any",axis=0)
df=pd.get_dummies(df).astype(int)

In [5]:
df

,Unnamed: 0,Kelas,Tahun,Nama Peserta_A A Anandika Parwata,Nama Peserta_A Agil Fikri,Nama Peserta_A Annisa Aulia Rimayanti,Nama Peserta_A Azizi,Nama Peserta_A Bahrul Ulum Azmi,Nama Peserta_A Kayan Manggala,Nama Peserta_A L Adliansyah,...,Bidang_Matematika,Jenjang Lomba_SMA,Jenjang Lomba_SMP,Jenjang Sekolah_SMA,Jenjang Sekolah_SMP,Medali_Emas,Medali_Harapan,Medali_Partisipan,Medali_Perak,Medali_Perunggu
0,0,11,2016,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,1,11,2021,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
2,2,11,2022,0,0,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,0
3,3,11,2022,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
4,4,11,2022,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19309,19309,8,2024,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
19320,19320,8,2024,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
19321,19321,8,2024,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
19322,19322,7,2024,0,0,0,0,0,0,0,...,1,0,1,0,1,0,0,1,0,0
19324,19324,7,2024,0,0,0,0,0,0,0,...,1,0,1,0,1,0,0,1,0,0

In [6]:
X=df.drop(columns=["Unnamed: 0","Kelas"])
Y=df["Kelas"]

In [7]:
Y.nunique()

5

In [8]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
for i in [RandomForestClassifier(),GradientBoostingClassifier(),AdaBoostClassifier(),BaggingClassifier(),KNeighborsClassifier(),SVC(),BernoulliNB()]:
    random_classif=i
    random_classif.fit(X_train,Y_train)
    print(f"The accuracy of {i}:",random_classif.score(X_test,Y_test))

The accuracy of RandomForestClassifier(): 0.6782228205991249
The accuracy of GradientBoostingClassifier(): 0.7411645910467856
The accuracy of AdaBoostClassifier(): 0.7408280040390441
The accuracy of BaggingClassifier(): 0.6819252776842814
The accuracy of KNeighborsClassifier(): 0.6607202961965668

# # # Quantum Deep learninig

In [ ]:
!pip install cirq

In [ ]:
import cirq
import tensorflow as tf
from keras.layers import Layer,Dense,Flatten,LSTM,SimpleRNN,GRU
from keras.models import Model,Sequential
from keras.initializers import HeNormal
from keras.regularizers import l2
from keras.callbacks import EarlyStopping

In [ ]:
def quantum_circuit(data):
    qubit=[cirq.GridQubit(0,i) for i in range(10)]
    circuit=cirq.Circuit()
    for i,value in enumerate(data): 
        q=i%len(qubit)
        circuit.append(cirq.H(qubit[q]))
        circuit.append(cirq.rx(value*np.pi).on(qubit[q]))
        circuit.append(cirq.ry(value*np.pi).on(qubit[q]))
        circuit.append(cirq.rz(value*np.pi).on(qubit[q]))
        if (i+2)%len(qubit)<len(qubit):
            circuit.append(cirq.CNOT(qubit[q],qubit[(i+1)%len(qubit)]))
            circuit.append(cirq.CCX(qubit[q],qubit[(i+1)%len(qubit)],qubit[(i+2)%len(qubit)]))
            circuit.append(cirq.measure(qubit[q],key=f"qubit_{i}"))       
    return circuit
def run_quantum_circuit(data):
    results=[]
    simulator=cirq.Simulator()
    for inputs_data in data:
        circuit=quantum_circuit(inputs_data)
        result=simulator.run(circuit)
        measure0=[]
        for i in range(len(data)):
            measure0.append(result.measurements[f"qubit_{i}"].flatten()[0])

        results.append(measure0)
    return np.array(results,dtype=np.float32)
class QuantumLayer(Layer): 
    def __init__(self):
        super(QuantumLayer,self).__init__()
    def call(self,inputs):
        inputs_shape=tf.reshape(inputs,(tf.shape(inputs)[0],tf.shape(inputs)[2]))
        output=tf.numpy_function(run_quantum_circuit,[inputs_shape],tf.float32)
        output.set_shape(inputs.shape)
        return output
model=Sequential([
    QuantumLayer(),
    LSTM(32,activation="relu",return_sequences=False),
    Flatten(),
    Dense(5,activation="softmax")
])
model.compile(optimizer='adam',loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [ ]:
X_train_reshape=X_train.values
X_train_reshape=np.reshape(X_train_reshape,(X_train_reshape.shape[0],1,X_train_reshape.shape[1]))
X_train_reshape.shape

In [ ]:
model.fit(X_train_reshape[:10,:10],Y_train[:10])